(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.DASimulator=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='1.0.0';
function u32(v,f=12345){const n=Number(v);return Number.isFinite(n)?Math.floor(n)>>>0:f>>>0;}
function rngFor(seed){let s=u32(seed);return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function roll(rng,sides){return Math.floor(rng()*Math.max(1,Math.floor(sides)))+1;}
function normalizeBlueprint(input){const b=JSON.parse(JSON.stringify(input||{}));b.schema='sim-da-blueprint';b.schemaVersion=1;b.simulator='dice-difference';b.engineVersion=VERSION;b.name=String(b.name||'Dice Difference Blueprint');b.roster=b.roster||{};b.armyA=b.armyA||{};b.armyB=b.armyB||{};b.config=Object.assign({diceMode:'single',dieASides:10,dieBSides:20,pctPerPoint:2,nestedPenalty:10,numStages:10,aKnightBonusPct:0,bKnightBonusPct:0,seed:12345},b.config||{});b.config.seed=u32(b.config.seed);return b;}
function totals(comp,roster){let atk=0,def=0;for(const k of Object.keys(roster)){const count=Math.max(0,Number(comp[k])||0);atk+=count*(Number(roster[k].atk)||0);def+=count*(Number(roster[k].def)||0);}return{atk,def};}
function modifier(rng,c){if(c.diceMode==='single'){const d=roll(rng,c.dieBSides),mid=c.dieBSides/2;return{modifier:(d-mid)*c.pctPerPoint,detail:`d${c.dieBSides}=${d}`};}const dA=roll(rng,c.dieASides),rolls=[];let total=0;for(let i=0;i<dA;i++){const d=roll(rng,c.dieBSides);rolls.push(d);total+=(d-c.dieBSides/2)*c.pctPerPoint;}const penalty=dA<c.dieASides/2?-c.nestedPenalty:0;return{modifier:total+penalty,detail:`d${c.dieASides}=${dA}; ${dA}×d${c.dieBSides}=[${rolls.join(', ')}]; penalty=${penalty}%`};}
function runBattle(blueprint,seed,includeStages=true){const b=normalizeBlueprint(blueprint),c=b.config,rng=rngFor(seed??c.seed),a=totals(b.armyA,b.roster),d=totals(b.armyB,b.roster);const aAtk=a.atk*(1+c.aKnightBonusPct/100),aDef=a.def*(1+c.aKnightBonusPct/100),bAtk=d.atk*(1+c.bKnightBonusPct/100),bDef=d.def*(1+c.bKnightBonusPct/100);let aTotal=0,bTotal=0;const stages=[];for(let stage=1;stage<=Math.max(1,Math.floor(c.numStages));stage++){const ar=modifier(rng,c),br=modifier(rng,c),am=ar.modifier/100,bm=br.modifier/100,ap=Math.max(0,aAtk*(1+am)-bDef*(1-bm)),bp=Math.max(0,bAtk*(1+bm)-aDef*(1-am));aTotal+=ap;bTotal+=bp;if(includeStages)stages.push({stage,aModifierPct:ar.modifier,bModifierPct:br.modifier,aRollDetail:ar.detail,bRollDetail:br.detail,aPower:ap,bPower:bp});}const margin=aTotal-bTotal;return{seed:u32(seed??c.seed),winner:margin>0?'A':margin<0?'B':'Draw',margin,aTotal,bTotal,aBaseAtk:aAtk,aBaseDef:aDef,bBaseAtk:bAtk,bBaseDef:bDef,armyA:b.armyA,armyB:b.armyB,stages};}
function runMany(blueprint,count=100){const b=normalizeBlueprint(blueprint),n=Math.max(1,Math.floor(count));let aWins=0,bWins=0,draws=0,sumAbs=0,sum=0,max=0,min=Infinity;for(let i=0;i<n;i++){const r=runBattle(b,(b.config.seed+i)>>>0,false),m=Math.abs(r.margin);if(r.winner==='A')aWins++;else if(r.winner==='B')bWins++;else draws++;sumAbs+=m;sum+=r.margin;max=Math.max(max,m);min=Math.min(min,m);}return{count:n,baseSeed:b.config.seed,lastSeed:(b.config.seed+n-1)>>>0,aWins,bWins,draws,aWinPct:aWins/n*100,bWinPct:bWins/n*100,drawPct:draws/n*100,averageMargin:sumAbs/n,averageSignedMargin:sum/n,largestMargin:max,smallestMargin:min};}
return{VERSION,normalizeBlueprint,runBattle,runMany};
});
